version: "3.4"

services:
  app:
    image: "climbcomp/climbcomp-go:${DOCKER_TAG:-latest}"
    build:
      context: "."
      target: "${DOCKER_TARGET:-dev}"
    environment:
      - GH_TOKEN
      - TRAVIS_BRANCH
      - TRAVIS_PULL_REQUEST
      - TRAVIS_REPO_SLUG
      - VERSION_SRC_PATH=./climbcomp/climbcomp.go
    volumes:
      - ".:/go/src/app"
