#!/usr/bin/env bash
set -euo pipefail

CURRENT_BRANCH="$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)"

GH_TOKEN=${GH_TOKEN:?} # Required
TRAVIS_BRANCH=${TRAVIS_BRANCH:-$CURRENT_BRANCH}
TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST:-false}
TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG:?} # Required

REPO_URL="https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
# shellcheck disable=SC2002
VERSION="$(cat ./VERSION | xargs)"
GIT_TAG="v${VERSION}"


function ensure-branch-is-master {
    if [ "${TRAVIS_BRANCH}" != "master" ]; then
        echo "TRAVIS_BRANCH is not master: ${TRAVIS_BRANCH}"
        exit 0
    fi
}

function ensure-not-pull-request {
    if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then
        echo "TRAVIS_PULL_REQUEST is not false: ${TRAVIS_PULL_REQUEST}"
        exit 0
    fi
}

function ensure-not-already-tagged {
    echo "Fetching latest tags..."
    git fetch --tags "${REPO_URL}" > /dev/null 2>&1
    if [ "$(git tag -l "${GIT_TAG}")" != "" ]; then
        echo "Tag already exists: ${GIT_TAG}"
        exit 0
    fi
}

function create-git-tag {
    if [ "$(git config user.email)" == "" ]; then
        git config user.email "travis@travis-ci.org"
    fi
    if [ "$(git config user.name)" == "" ]; then
        git config user.name "Travis CI"
    fi
    echo "Tagging new version: ${GIT_TAG}"
    git tag -a "${GIT_TAG}" -m "Release of version ${VERSION}"
    git push -q "${REPO_URL}" --tags > /dev/null 2>&1
}


ensure-branch-is-master
ensure-not-pull-request
ensure-not-already-tagged
create-git-tag
